spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bulletin_board?characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
    username: ${DB_USER:appuser}
    password: ${DB_PASS:password}
